### ISSUE TITLE
Version number 2.0

### ISSUE THREAD

**Issue by koriym** [madapaja/Madapaja.TwigModule#16]
Why release v2.0.0 ? I think it should be 1.x. (=1.2.0).
But wait, we need some other discussion for stable release.

**Comment by madapaja** [comment]
@koriym 
I wrote in the Japanese.

PR #15 をマージした後、このプルリクエストがBC brakeがあると思いました。
PC brake がある場合、semantic versioning では後方互換性の無い場合、メジャーバージョンを上げる必要があると思い 2.0.0 としました。が、この判断（私の理解）は間違っているかもしれません。

以下、私が曖昧な2つの点を上げます。

1. BC brake の考え方
  Madapaja.TwigModule をバージョンアップした場合、このモジュールの依存性の問題で他のライブラリのバージョンを変更しなければいけない可能性があります。これを BC brake を捉えるのかが良く理解できていません。
2. Semantic Versioning の考え方
  semantic versioning には `MAJOR version when you make incompatible API changes,` とありますが、このような変更は今回行われていません。
  ただし、マイナー、パッチバージョンについては `backwards-compatible` が必要です。

どのように捉えるのが適切か、お考えを聞かせていただけるとありがたいです。
以上、よろしくお願いします。

追伸：新しいリリースを急いで行ってしまったのは、誤りだったと思います。事前に検討すべきでした。申し訳ないです。

**Comment by koriym** [comment]
`1`ですが互換性失われてないので大丈夫です。利用者からのAPIの互換性は壊れてません。

**Comment by koriym** [comment]
`phpunit`の要求バージョンは`require-dev`なので、このプロジェクトがメインの時のみ作用します。（依存される時は関係ありません）

**Comment by madapaja** [comment]
今回の場合、利用者からのAPIについては何も変わっていないため、前のバージョンが1.1.0なので、1.1.1 or 1.2.0 とするのが適切だったということですね。
早まってしまいました :sweat:

**Comment by madapaja** [comment]
今回は機能的な追加などは特に行われていませんので、本来はパッチバージョンをあげるのが適当なのかと思いますが、それについてはどう思いますでしょうか？

**Comment by koriym** [comment]
よく考えたら利用者側から特に何かを解決したわけでもないので`1.1.1`も要らないと思うのですがどうでしょうか。

**Comment by koriym** [comment]
packageist見るとまだインストールもないのでブランチ消しましょうか

**Comment by madapaja** [comment]
なるほど。確かに利用者目線では何も変わっていないため、バージョン番号を付ける必要がないですね。。。
ブランチ消しました。
お騒がせしました！

**Comment by koriym** [comment]
了解です！
