### ISSUE TITLE
テンプレートの場所

### ISSUE THREAD

**Issue by koriym** [madapaja/Madapaja.TwigModule#2]
> テンプレートはどこに置けばいいのだろうか、、、
> https://twitter.com/madapaja/status/552062047580475392

`0.x`と同じようにクラスファイルと同じ場所はどうでしょうか。

**Comment by madapaja** [comment]
@koriym
コメントありがとうございます。
クラスファイルと同じ場所、というのは ResourceObjectクラスと同じ場所、という意味でしょうか？
現状、基本的にはそうなっているのですが、その場合、レイアウトファイルやインクルードするパーツファイルのような物をどこに置くべきかで悩んでいます。

ResourceObject が

```
 - Resource/
    - App/
        - Greeting/
            - Index.php
```

のような場合、レイアウトファイルやインクルードするパーツファイルを以下のように配置するとレイアウトやパーツはリソースに付随したものではないため違和感があります。

```
 - Resource/
    - App/
        - Greeting/
            - Index.php
            - Index.html.twig
        - Layout/
            - Base.html.twig
        - Part/
            - RightMenu.html.twig
```

以下の様な配置の方がまだいいかもしれないですが、自信がありません。。。

```
 - Resource/
    - App/
        - Greeting/
            - Index.php
            - Index.html.twig
 - Template/
    - Layout/
        - Base.html.twig
    - Part/
        - RightMenu.html.twig
```

（とりとめのないissueですみません）

**Comment by koriym** [comment]
> とりとめのないissueですみません

いえいえ、大事でなかなか難しい問題です。

`0.x`ではこうしていました。

```
 - src/Resource/
    - App/
        - Greeting/
            - Index.php
            - Index.twig
 - var/lib/twig/
    - layout/
        - default.twig
    - part/
        - right_menu.twig
```
- `var/lib/`にはオプションでインストールしたライブラリの関連ファイルを入れるようにします。
- 大文字始まりはクラス名、それ以外は小文字ファイル名
