### ISSUE TITLE
拡張子

### ISSUE THREAD

**Issue by koriym** [madapaja/Madapaja.TwigModule#3]
`.twig`の方が`.html.twig`より一般的ではないかと思ったのですがどうでしょうか？

**Comment by madapaja** [comment]
Symfonyのマニュアルでは、`.html.twig` が使用されており、現状、それに則っています。
http://symfony.com/doc/current/book/templating.html

ただ、Twigのマニュアルでは `.html` で解説されているようです。
http://twig.sensiolabs.org/doc/templates.html

特に推奨する拡張子の記述などはないようですが、TwigModule のコンストラクタなどで拡張子を変更できるようにしておいた方が良いかもしれませんね。

**Comment by koriym** [comment]
そうなんですね。確かにテンプレートがhtmlに限らないと考えると理にかなってるかもしれませんね。
