### ISSUE TITLE
Twig extension を追加したい場合、どのようにすればいいか？

### ISSUE THREAD

**Issue by madapaja** [madapaja/Madapaja.TwigModule#9]
TwigModule をinstallすると、Twig_Environment がDIされるようになるので、そのインスタンスを取得して、そこからextensionの追加などできそうですが、具体的にどこにどのように記述すればいいか

**Comment by koriym** [comment]
候補１：ダブルプロバイダー
- Twig_Environment:@Named("original")に`TwigSourcePorvider`を束縛、モジュールの設定通りのTwigを提供
- Twig_Environmentに`MyTwigPorvider`を束縛、Twig_Environment `@Named("original")`で`Twig_Environment`を受けっとって`get()`メソッド内で`addExtension`などして提供。

**Comment by koriym** [comment]
@madapaja これを解決しましょうか

**Comment by madapaja** [comment]
はい！やります！

**Comment by koriym** [comment]
Twig 2.0 (php7.0+)のタイミングでいいかとも思いましたがここで直してそのまま Twig2.0がいいですね。

**Comment by koriym** [comment]
結局Twigをdecorateしないといけないわけだから、TwigProviderみたいなのを用意してユーザーが入れ替えれるようにするのがいいですかね

**Comment by madapaja** [comment]
その方向で実装してみようと思います！

**Comment by koriym** [comment]
手伝えることあったら言ってください。この機にdebug用のhtml viewも追加したらどうかと思ってます。

**Comment by koriym** [comment]
WhoopsかBEAR.Sunday 0.xで採用してたやつか

**Comment by madapaja** [comment]
#19 で対応します

**Comment by madapaja** [comment]
@koriym 
https://github.com/madapaja/Madapaja.TwigModule/issues/9#issuecomment-305422760 
についてですが、デバッグ時やエラー時の画面については Twig とは関係なく、
また、whoops であれば https://github.com/franzliedke/whoops-middleware で PSR-7 middleware などで追加も可能なので不要かなと思っています。
（ユーザーが好きな物を使えば良く、このモジュールでの追加が必要なのか？という点です）

**Comment by madapaja** [comment]
ちなみに、BEAR.Sunday 0.xでは何を採用していたのでしょうか？

**Comment by koriym** [comment]
そうですね。`html`コンテキストでJSONの代わりにHTMLエラー画面が出ればいいと思ったのですが、それを`HtmlErrorModule`など別のモジュールにすればいいですね。

**Comment by koriym** [comment]
`0.x`ではオリジナルです。

試して見てください。結構面白いですよ。
https://github.com/bearsunday/BEAR.Package/tree/0.x

```
$ composer create-project bear/package BEAR0 ~0.13
$ cd BEAR0
$ php apps/Demo.Sandbox/bin/install_db.sh
$ bin/bear.server apps/Demo.Sandbox
```

**Comment by koriym** [comment]
503 などデバックではないのエラーを出すことを考えるとどうでしょうか？
`var/twig/http_error/503.hml.twig`
などのテンプレートを表示するような仕組みはどうでしょうか。

**Comment by madapaja** [comment]
そうですね。
デバッグ用のモジュールは別切り出しで、
TwigModule では http エラーコードに応じたエラー画面表示の仕組は入れても良さそうです！

**Comment by koriym** [comment]
反映しました。リリースします。
エラーページはまた次に。
